// Interactive Learning Content for LKG-1st (Ages 4-6)

// Color Learning with Brush Painting Animation
export const COLOR_CARDS = [
  {
    id: 'red',
    color: '#EF4444',
    name: 'Red',
    telugu: 'ఎరుపు',
    hindi: 'लाल',
    image: 'https://static.prod-images.emergentagent.com/jobs/80d92d7f-316a-41ab-bd79-1d754a01b3fc/images/41480abe1aa34cf97f969d99751f1c9e8d4e0202edc6ff5dee7e2525b4ab1c4d.png',
    examples: ['Apple', 'Heart', 'Fire truck'],
    question: 'What color is this?',
  },
  {
    id: 'blue',
    color: '#3B82F6',
    name: 'Blue',
    telugu: 'నీలం',
    hindi: 'नीला',
    image: 'https://static.prod-images.emergentagent.com/jobs/80d92d7f-316a-41ab-bd79-1d754a01b3fc/images/29d3b8f918440dbd2b32e975f60f0ba71f5cfdbabe6e2fb8310260195d5a4ec7.png',
    examples: ['Sky', 'Ocean', 'Blueberry'],
    question: 'What color is this?',
  },
  {
    id: 'yellow',
    color: '#F59E0B',
    name: 'Yellow',
    telugu: 'పసుపు',
    hindi: 'पीला',
    image: 'https://static.prod-images.emergentagent.com/jobs/80d92d7f-316a-41ab-bd79-1d754a01b3fc/images/5fea72e999972be04b437defcccb59441ffda598fef701d6f4a221e635069c8b.png',
    examples: ['Sun', 'Banana', 'Lemon'],
    question: 'What color is this?',
  },
  {
    id: 'green',
    color: '#10B981',
    name: 'Green',
    telugu: 'ఆకుపచ్చ',
    hindi: 'हरा',
    image: 'https://static.prod-images.emergentagent.com/jobs/80d92d7f-316a-41ab-bd79-1d754a01b3fc/images/c8ccfc6a00c6d0366287ef9029eb931137547b80729a58a0fbafaeff1ff8f488.png',
    examples: ['Grass', 'Leaves', 'Frog'],
    question: 'What color is this?',
  },
  {
    id: 'orange',
    color: '#F97316',
    name: 'Orange',
    telugu: 'నారింజ',
    hindi: 'नारंगी',
    examples: ['Orange fruit', 'Carrot', 'Pumpkin'],
    question: 'What color is this?',
  },
  {
    id: 'purple',
    color: '#8B5CF6',
    name: 'Purple',
    telugu: 'ఊదా',
    hindi: 'बैंगनी',
    examples: ['Grapes', 'Eggplant', 'Violet flower'],
    question: 'What color is this?',
  },
  {
    id: 'pink',
    color: '#EC4899',
    name: 'Pink',
    telugu: 'గులాబీ',
    hindi: 'गुलाबी',
    examples: ['Flamingo', 'Rose', 'Cotton candy'],
    question: 'What color is this?',
  },
  {
    id: 'white',
    color: '#F9FAFB',
    name: 'White',
    telugu: 'తెలుపు',
    hindi: 'सफेद',
    examples: ['Cloud', 'Snow', 'Milk'],
    question: 'What color is this?',
  },
  {
    id: 'black',
    color: '#1F2937',
    name: 'Black',
    telugu: 'నలుపు',
    hindi: 'काला',
    examples: ['Night sky', 'Crow', 'Coal'],
    question: 'What color is this?',
  },
];

// Family Members Learning
export const FAMILY_CARDS = [
  {
    id: 'mom',
    name: 'Mom',
    telugu: 'అమ్మ',
    hindi: 'माँ',
    fullName: 'Mother',
    image: 'https://static.prod-images.emergentagent.com/jobs/80d92d7f-316a-41ab-bd79-1d754a01b3fc/images/65f2a0d3b3f1e89515aef6ecb60d386d0a816e4dc3bf7377cfdc7f6c5359c71d.png',
    description: 'She loves you and takes care of you!',
    question: 'Who is this?',
  },
  {
    id: 'dad',
    name: 'Dad',
    telugu: 'నాన్న',
    hindi: 'पापा',
    fullName: 'Father',
    image: 'https://static.prod-images.emergentagent.com/jobs/80d92d7f-316a-41ab-bd79-1d754a01b3fc/images/2ff3f27e3efaf80cc5193d3dc54087953ccf0ea448172361aba85fddc33c6f0d.png',
    description: 'He protects you and plays with you!',
    question: 'Who is this?',
  },
  {
    id: 'grandma',
    name: 'Grandma',
    telugu: 'నానమ్మ',
    hindi: 'दादी',
    fullName: 'Grandmother',
    image: 'https://static.prod-images.emergentagent.com/jobs/80d92d7f-316a-41ab-bd79-1d754a01b3fc/images/885feeaf8851dbb5ff5e10bc97cef89091193c4c29d1fd0ed020366568907030.png',
    description: 'She tells you stories and gives you treats!',
    question: 'Who is this?',
  },
  {
    id: 'family',
    name: 'Family',
    telugu: 'కుటుంబం',
    hindi: 'परिवार',
    fullName: 'My Family',
    image: 'https://static.prod-images.emergentagent.com/jobs/80d92d7f-316a-41ab-bd79-1d754a01b3fc/images/adc752a03106f08b07e5333f74b552fb7dbd1bc17d1a518ee8dd1110072cf1ef.png',
    description: 'People who love you!',
    question: 'What is this called?',
  },
];

// Body Parts Learning
export const BODY_PARTS_CARDS = [
  {
    id: 'eyes',
    name: 'Eyes',
    telugu: 'కళ్ళు',
    hindi: 'आँखें',
    image: 'https://static.prod-images.emergentagent.com/jobs/80d92d7f-316a-41ab-bd79-1d754a01b3fc/images/9e5dba6c5b87a2e6be37ee7d06066243343c9f3d1076c428173d8c40fd424023.png',
    action: 'We use eyes to see!',
    question: 'What do we use to see?',
    song: '👀 Eyes, eyes, we use to see, Beautiful things like you and me!',
  },
  {
    id: 'nose',
    name: 'Nose',
    telugu: 'ముక్కు',
    hindi: 'नाक',
    image: 'https://static.prod-images.emergentagent.com/jobs/80d92d7f-316a-41ab-bd79-1d754a01b3fc/images/4af4b48cf508a5b23c382ba692e2244550963c397683c618d6b32dc7e8b62d30.png',
    action: 'We use nose to smell!',
    question: 'What do we use to smell flowers?',
    song: '👃 Nose, nose, helps us smell, Flowers and food, it does it well!',
  },
  {
    id: 'hands',
    name: 'Hands',
    telugu: 'చేతులు',
    hindi: 'हाथ',
    image: 'https://static.prod-images.emergentagent.com/jobs/80d92d7f-316a-41ab-bd79-1d754a01b3fc/images/051372ca9d09fc3caa87812c6eda494f17258c53b542fa4923c47890aea3f54e.png',
    action: 'We use hands to hold things!',
    question: 'What do we use to wave hello?',
    song: '👋 Hands, hands, wave and clap, Hold a toy or take a nap!',
  },
  {
    id: 'ears',
    name: 'Ears',
    telugu: 'చెవులు',
    hindi: 'कान',
    action: 'We use ears to hear!',
    question: 'What do we use to listen to music?',
    song: '👂 Ears, ears, help us hear, Music, voices, far and near!',
  },
  {
    id: 'mouth',
    name: 'Mouth',
    telugu: 'నోరు',
    hindi: 'मुँह',
    action: 'We use mouth to talk and eat!',
    question: 'What do we use to eat food?',
    song: '👄 Mouth, mouth, helps us talk, Eat our food, sing and walk!',
  },
  {
    id: 'feet',
    name: 'Feet',
    telugu: 'పాదాలు',
    hindi: 'पैर',
    action: 'We use feet to walk and run!',
    question: 'What do we use to run?',
    song: '🦶 Feet, feet, help us run, Jump and dance, so much fun!',
  },
];

// Shapes Learning
export const SHAPES_CARDS = [
  {
    id: 'circle',
    name: 'Circle',
    telugu: 'వృత్తం',
    hindi: 'गोल',
    color: '#EF4444',
    examples: ['Sun', 'Ball', 'Cookie', 'Clock'],
    image: 'https://static.prod-images.emergentagent.com/jobs/80d92d7f-316a-41ab-bd79-1d754a01b3fc/images/26cddf51d742d6c55377432f8ca9cd4ec783c2d6162e9f2a9ed3f6a2950de155.png',
    question: 'What shape is the sun?',
    description: 'Round like a ball!',
  },
  {
    id: 'square',
    name: 'Square',
    telugu: 'చతురస్రం',
    hindi: 'चौकोर',
    color: '#3B82F6',
    examples: ['Window', 'TV', 'Cracker', 'Tile'],
    question: 'What shape is a window?',
    description: 'Four equal sides!',
  },
  {
    id: 'triangle',
    name: 'Triangle',
    telugu: 'త్రికోణం',
    hindi: 'तिकोना',
    color: '#10B981',
    examples: ['Roof', 'Pizza slice', 'Mountain', 'Tent'],
    question: 'What shape is a pizza slice?',
    description: 'Three sides!',
  },
  {
    id: 'rectangle',
    name: 'Rectangle',
    telugu: 'దీర్ఘచతురస్రం',
    hindi: 'आयत',
    color: '#F59E0B',
    examples: ['Door', 'Book', 'Phone', 'Chocolate bar'],
    question: 'What shape is a door?',
    description: 'Like a stretched square!',
  },
  {
    id: 'star',
    name: 'Star',
    telugu: 'నక్షత్రం',
    hindi: 'तारा',
    color: '#F59E0B',
    examples: ['Stars in sky', 'Starfish', 'Star sticker'],
    question: 'What shape twinkles in the sky?',
    description: 'Five points!',
  },
  {
    id: 'heart',
    name: 'Heart',
    telugu: 'హృదయం',
    hindi: 'दिल',
    color: '#EC4899',
    examples: ['Love symbol', 'Valentine card'],
    question: 'What shape shows love?',
    description: 'The shape of love!',
  },
];

// Daily Session Activities
export const DAILY_SESSION = {
  phonics: {
    title: 'Phonics Corner',
    duration: '3 minutes',
    activities: [
      {
        id: 'alphabet_song',
        name: 'Alphabet Song',
        description: 'Sing along with the ABC song!',
        type: 'song',
      },
      {
        id: 'letter_sound',
        name: 'Letter Sounds',
        description: 'Learn what sound each letter makes!',
        type: 'interactive',
      },
      {
        id: 'rhyming',
        name: 'Rhyming Game',
        description: 'Find words that sound the same!',
        type: 'game',
      },
    ],
  },
  coreSkills: {
    title: 'Core Skills',
    duration: '5 minutes',
    age2: {
      focus: 'Body parts, objects, and family',
      technique: 'Total Immersion - describe actions',
      example: 'Mummy is putting the clothes in the drawer',
    },
    age3: {
      focus: '5-6 word sentences',
      technique: 'Open-ended questions',
      example: 'What would you like for breakfast?',
    },
    age4: {
      focus: 'Following directions and retelling stories',
      technique: 'Logical steps',
      example: 'First put on your socks, then put on your shoes',
    },
  },
  fineMotor: {
    title: 'Fun Activities',
    duration: '4 minutes',
    activities: [
      {
        id: 'magnet_fishing',
        name: 'Magnet Fishing',
        description: 'Catch letters and say words that start with them!',
        icon: '🎣',
      },
      {
        id: 'alphabet_tracing',
        name: 'Letter Tracing',
        description: 'Trace letters with your finger!',
        icon: '✏️',
      },
      {
        id: 'sticker_lineup',
        name: 'Sticker Fun',
        description: 'Place stickers on the path!',
        icon: '⭐',
      },
    ],
  },
  reading: {
    title: 'Story Time',
    duration: '3 minutes',
    technique: 'Reading with Gaps',
    description: 'Fill in the missing word in the story!',
    example: 'The cat sat on the ___',
  },
};

// Parental Tips
export const PARENTAL_TIPS = [
  {
    id: 'speech_modeling',
    title: 'Model Correct Speech',
    tip: "If your child says 'tu' for 'soup', respond with 'Yes, that's soup!' without correcting them directly.",
    importance: 'high',
  },
  {
    id: 'screen_time',
    title: 'Screen Time Limit',
    tip: 'Limit total screen time to under one hour per day for young children.',
    importance: 'high',
  },
  {
    id: 'encouragement',
    title: 'Positive Encouragement',
    tip: 'Celebrate small wins! Every new word learned is a victory.',
    importance: 'medium',
  },
  {
    id: 'daily_routine',
    title: 'Make it a Routine',
    tip: 'Set a fixed time each day for learning - consistency helps retention.',
    importance: 'medium',
  },
  {
    id: 'real_world',
    title: 'Connect to Real World',
    tip: 'Point out colors, shapes, and objects during daily activities.',
    importance: 'medium',
  },
];

// Interactive Learning Categories for LKG-1st
export const LKG_LEARNING_CATEGORIES = [
  {
    id: 'colors',
    name: 'Colors',
    icon: '🎨',
    color: '#EC4899',
    description: 'Learn colors with painting!',
    cards: COLOR_CARDS,
  },
  {
    id: 'family',
    name: 'Family',
    icon: '👨‍👩‍👧',
    color: '#F59E0B',
    description: 'Know your family members!',
    cards: FAMILY_CARDS,
  },
  {
    id: 'body',
    name: 'Body Parts',
    icon: '🙋',
    color: '#10B981',
    description: 'Learn about your body!',
    cards: BODY_PARTS_CARDS,
  },
  {
    id: 'shapes',
    name: 'Shapes',
    icon: '⭐',
    color: '#3B82F6',
    description: 'Discover fun shapes!',
    cards: SHAPES_CARDS,
  },
];
